### ISSUE TITLE
Question Regarding NullPointerException in GetListOfCurrentUsersPlaylistsRequest

### ISSUE THREAD

**Issue by robinfriedli** [thelinmichael/spotify-web-api-java#241] opened 2021-02-04 18:48 UTC
Hi,

This is more of a question than a bug report, but I've noticed for a while now that sometimes after running the application for a while (1 week+) the `GetListOfCurrentUsersPlaylistsRequest` starts throwing a NullPointerException consistently for every single request. Restarting the application fixes the issue immediately. I've actually first run into this issue quite a while back, probably more than a year, and granted, the production version of the application still uses an old version of the API wrapper (5.0.4) (the update to v6+ caused quite a big change in the code base that was implemented in the development branch of the application, which is not ready for release) but sometimes the issue does not arise for a while. The exception is caused by `AbstractRequest#getJson` returning null, throwing the NPE when trying to call `String#length` in `StringReader#<init>`:
```
Caused by: java.lang.NullPointerException
	at java.io.StringReader.<init>(StringReader.java:50)
	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
	at com.wrapper.spotify.model_objects.AbstractModelObject$JsonUtil.createModelObjectPaging(AbstractModelObject.java:149)
	at com.wrapper.spotify.requests.data.playlists.GetListOfCurrentUsersPlaylistsRequest.execute(GetListOfCurrentUsersPlaylistsRequest.java:39)
```

However, the reason why `AbstractRequest#getJson` returns null seems to be that the endpoint returns an invalid response, either null or an empty string:
```
  public String getJson() throws
    IOException,
    SpotifyWebApiException,
    ParseException {
    String json = httpManager.get(uri, headers.toArray(new Header[0]));

    if (json == null || json.equals("")) {
      return null;
    } else {
      return json;
    }
  }
```

So my main question is: does this even have anything to do with the API wrapper or is it an issue with the API? And: is this by chance a known issue that has already been fixed? The fact that rebooting the application fixes the issue seems to indicate that it is the wrapper that's causing the error, but the fact that the wrapper receives that response seems to indicate that it is something to to with the API, unless it somehow has something to do with the headers the wrapper provides.

**Comment by dargmuesli** [comment] 2021-02-04 19:22
That's new to me. It would be helpful to know for which requested data the request fails.
In general only the most recent major version of this project is actively supported, so it would be great if you could check if this error persists with v6. Thanks for the detailed report though!

**Comment by robinfriedli** [comment] 2021-02-05 14:34
Unfortunately it could be a while until I update production. It would certainly be interesting to know the exact request including all headers that are sent when the request fails, does the wrapper offer trace / debug logs for that? I couldn't reproduce the issue locally / any environment other than production. All I currently know is that ALL GetListOfCurrentUsersPlaylistsRequest start to fail for every user but all other requests that I use still work fine. Actually now that I think about it I could check whether `checkUsersSavedTracks` and `checkUsersSavedAlbums` still work next time it happens, I don't use these often so I'm not sure, but they're the only other requests where I use user authentication and not just client authentication. I kinda doubt it's an authentication issue because then I'd expect the API to return a 403 and the wrapper to throw an UnauthorizedException but it's worth checking. Anyway, why main query was whether this as a known issue / easily explainable behaviour. I've been running the current build of the development branch for about a week now (which is using 6.5.1) and so far I can't reproduce it there.

**Comment by dargmuesli** [comment] 2021-02-05 16:27
The project you are referencing is https://github.com/robinfriedli/botify?

**Comment by robinfriedli** [comment] 2021-02-05 17:26
yes

**Comment by dr75** [comment] 2021-03-15 13:51
Hi! I get the same for artist requests:

```
Exception in thread "Thread-0" java.lang.NullPointerException
	at java.base/java.io.StringReader.<init>(StringReader.java:50)
	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
	at com.wrapper.spotify.model_objects.AbstractModelObject$JsonUtil.createModelObjectPaging(AbstractModelObject.java:162)
	at com.wrapper.spotify.requests.data.search.simplified.SearchArtistsRequest.execute(SearchArtistsRequest.java:41)
```

As `AbstractRequest.getJson()` returns `null`, this is forwarded to `createModelObjectPaging()` - so same as above.

The null value comes from `SpotifyHttpManager.getResponseBody()` I think. There, not all potential error cases are handled such that a return of null seems natural. But I cannot say what the cause was.

**Comment by robinfriedli** [comment] 2021-03-16 18:53
And I've just run into the issue again after upgrading to 6.5.2 at ~9 days uptime

**Comment by dargmuesli** [comment] 2021-03-16 18:55
Ok, I see this report as a confirmed bug, eventhough I'm currently out of time for testing of fixing it myself. Help is of course appreciated, otherwise I'll take care of it when I have some free time.

**Comment by robinfriedli** [comment] 2021-03-16 21:35
I'll temporarily log request parameters before executing a GetListOfCurrentUsersPlaylistsRequest and check what happens if I try executing the request with the same access token from somewhere else when I run into the issue again, it's a long shot but it helps ruling out any issues with the Spotify API if the endpoint still returns valid JSON responses. Additionally I've enabled all logging messages for the com.wrapper.spotify.SpotifyApi logger, I noticed that the SpotifyHttpManager logs whether the response was fetched from the cache and I suspect it might be a caching issue.

**Comment by robinfriedli** [comment] 2021-04-04 14:25
So I've just run into the issue again and can confirm that when trying the request with the same params and token on developer.spotify.com, the endpoint seems to return a valid JSON, so the issue does seem to be caused by the wrapper. However, the SpotifyApi logger still reports that the response is coming from an upstream server, so it probably isn't a caching issue.
Exemplary log entry:
```
[DEBUG] 2021-04-04 14:17:10.372 [botify command execution: CommandContext@deded585-9398-4009-9373-975d86b5fbd7] SpotifyService - Executing GetListOfCurrentUsersPlaylistsRequest with params: token ...; offset 0; limit 50; uri https://api.spotify.com:443/v1/me/playlists?offset=0&limit=50, headers [Authorization: Bearer ...], body null
Apr 04, 2021 2:17:10 PM com.wrapper.spotify.SpotifyHttpManager execute
CONFIG: The response came from an upstream server
[ERROR] 2021-04-04 14:17:10.411 [botify command execution: CommandContext@deded585-9398-4009-9373-975d86b5fbd7] CommandManager - Exception while handling command .psol songs on guild botify
net.robinfriedli.botify.exceptions.CommandRuntimeException: java.lang.NullPointerException
        at net.robinfriedli.botify.command.interceptor.interceptors.CommandExecutionInterceptor.intercept(CommandExecutionInterceptor.java:125) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.command.interceptor.AbstractChainableCommandInterceptor.intercept(AbstractChainableCommandInterceptor.java:36) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.command.interceptor.AbstractChainableCommandInterceptor.intercept(AbstractChainableCommandInterceptor.java:36) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.command.interceptor.AbstractChainableCommandInterceptor.intercept(AbstractChainableCommandInterceptor.java:36) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.command.interceptor.AbstractChainableCommandInterceptor.intercept(AbstractChainableCommandInterceptor.java:36) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.command.interceptor.AbstractChainableCommandInterceptor.intercept(AbstractChainableCommandInterceptor.java:36) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.command.interceptor.CommandInterceptorChain.intercept(CommandInterceptorChain.java:69) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.command.CommandManager.lambda$runCommand$0(CommandManager.java:56) ~[botify-1.0-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
        at net.robinfriedli.botify.concurrent.QueuedThread.run(QueuedThread.java:18) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.concurrent.CommandExecutionThread.run(CommandExecutionThread.java:23) ~[botify-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.NullPointerException
        at java.io.StringReader.<init>(StringReader.java:50) ~[?:?]
        at com.google.gson.JsonParser.parseString(JsonParser.java:47) ~[botify-1.0-SNAPSHOT.jar:?]
        at com.wrapper.spotify.model_objects.AbstractModelObject$JsonUtil.createModelObjectPaging(AbstractModelObject.java:155) ~[botify-1.0-SNAPSHOT.jar:?]
        at com.wrapper.spotify.requests.data.playlists.GetListOfCurrentUsersPlaylistsRequest.execute(GetListOfCurrentUsersPlaylistsRequest.java:39) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.audio.spotify.SpotifyService.searchOwnPlaylist(SpotifyService.java:110) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.command.commands.AbstractPlayableLoadingCommand.lambda$loadSpotifyList$2(AbstractPlayableLoadingCommand.java:160) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.function.modes.SpotifyUserAuthorizationMode.lambda$wrap$0(SpotifyUserAuthorizationMode.java:28) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.exec.BaseInvoker.invoke(BaseInvoker.kt:17) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.function.SpotifyInvoker.invoke(SpotifyInvoker.java:49) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.function.SpotifyInvoker.invoke(SpotifyInvoker.java:53) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.command.AbstractCommand.runWithLogin(AbstractCommand.java:198) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.command.commands.AbstractPlayableLoadingCommand.loadSpotifyList(AbstractPlayableLoadingCommand.java:182) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.command.commands.AbstractPlayableLoadingCommand.doRun(AbstractPlayableLoadingCommand.java:71) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.command.commands.PlayCommand.doRun(PlayCommand.java:44) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.command.interceptor.interceptors.CommandExecutionInterceptor.intercept(CommandExecutionInterceptor.java:51) ~[botify-1.0-SNAPSHOT.jar:?]
        ... 10 more

```
(I replaced the actual token with ...)

**Comment by dargmuesli** [comment] 2021-04-04 19:11
I've now added a few log statements (https://github.com/thelinmichael/spotify-web-api-java/commit/4acb1e7f6a7e96c67adecf20237b29b5060a8716). Please use log level fine if not done already and check the log messages when the issue appears again.

**Comment by robinfriedli** [comment] 2021-04-14 01:21
It looks like the beviour is caused by the endpoint responding with a 431
```
[DEBUG] 2021-04-14 01:12:24.225 [botify command execution: CommandContext@cf09bd99-f564-4962-a65c-ed1348542b9b] SpotifyService - Executing GetListOfCurrentUsersPlaylistsRequest with params: token ...; offset 0; limit 50; uri https://api.spotify.com:443/v1/me/playlists?offset=0&limit=50, headers [Authorization: Bearer ...], body null
Apr 14, 2021 1:12:24 AM com.wrapper.spotify.SpotifyHttpManager execute
CONFIG: The response came from an upstream server
Apr 14, 2021 1:12:24 AM com.wrapper.spotify.SpotifyHttpManager getResponseBody
FINE: The http response has body 
Apr 14, 2021 1:12:24 AM com.wrapper.spotify.SpotifyHttpManager getResponseBody
FINE: The http response has status code 431
Apr 14, 2021 1:12:24 AM com.wrapper.spotify.requests.AbstractRequest returnJson
FINE: The httpManager returned json == "".
[ERROR] 2021-04-14 01:12:24.264 [botify command execution: CommandContext@cf09bd99-f564-4962-a65c-ed1348542b9b] CommandManager - Exception while handling command .search -spotify -own -list songs on guild botify
net.robinfriedli.botify.exceptions.CommandRuntimeException: java.lang.NullPointerException
        at net.robinfriedli.botify.command.interceptor.interceptors.CommandExecutionInterceptor.intercept(CommandExecutionInterceptor.java:125) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.command.interceptor.AbstractChainableCommandInterceptor.intercept(AbstractChainableCommandInterceptor.java:36) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.command.interceptor.AbstractChainableCommandInterceptor.intercept(AbstractChainableCommandInterceptor.java:36) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.command.interceptor.AbstractChainableCommandInterceptor.intercept(AbstractChainableCommandInterceptor.java:36) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.command.interceptor.AbstractChainableCommandInterceptor.intercept(AbstractChainableCommandInterceptor.java:36) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.command.interceptor.AbstractChainableCommandInterceptor.intercept(AbstractChainableCommandInterceptor.java:36) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.command.interceptor.CommandInterceptorChain.intercept(CommandInterceptorChain.java:69) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.command.CommandManager.lambda$runCommand$0(CommandManager.java:56) ~[botify-1.0-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
        at net.robinfriedli.botify.concurrent.QueuedThread.run(QueuedThread.java:18) ~[botify-1.0-SNAPSHOT.jar:?]
        at net.robinfriedli.botify.concurrent.CommandExecutionThread.run(CommandExecutionThread.java:23) ~[botify-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.NullPointerException
```
(token omitted)

Which is strange, because the only header set seems to be the JWT. Pretty sure that's it though, the log is pretty busy with messages but every failing request logs a 431 and the empty json response.

**Comment by robinfriedli** [comment] 2021-04-14 01:26
Also, using the very same token from this log entry on the [developer page](https://developer.spotify.com/console/get-current-user-playlists/) returns a valid json. Not sure if the client ends up adding additional headers that are causing the issue?

**Comment by dargmuesli** [comment] 2021-04-15 08:36
Header logging added in `6.5.4`: 44131e7b65fdd6bc398a4fbaa8a0ca9afe422c28

**Comment by robinfriedli** [comment] 2021-05-16 15:53
I've finally run into the issue again, I'll attach the log below. I've omitted the token but it was a 232 character long string, I doubt that this is the culprit.

```
[DEBUG] 2021-05-16 15:34:04.784 [botify command execution: CommandContext@01c85de9-1ad2-4fb9-a3e6-7538bab1d6cd] SpotifyService - Executing GetListOfCurrentUsersPlaylistsRequest with params: token ...; offset 0; limit 50; uri https://api.spotify.com:443/v1/me/playlists?offset=0&limit=50, headers [Authorization: Bearer ...], body null                                          
May 16, 2021 3:34:04 PM com.wrapper.spotify.SpotifyHttpManager get                                                                                                                                                                                                                    
FINE: GET request uses these headers: [{"name":"Authorization","sensitive":false,"value":"Bearer ..."}]                                                                                                                                                                                                                                
May 16, 2021 3:34:04 PM com.wrapper.spotify.SpotifyHttpManager execute                                                                                                                                                                                                                
CONFIG: The response came from an upstream server
May 16, 2021 3:34:04 PM com.wrapper.spotify.SpotifyHttpManager getResponseBody                                                             
FINE: The http response has body 
May 16, 2021 3:34:04 PM com.wrapper.spotify.SpotifyHttpManager getResponseBody                                                             
FINE: The http response has status code 431
May 16, 2021 3:34:04 PM com.wrapper.spotify.requests.AbstractRequest returnJson                                                            
FINE: The httpManager returned json == "".
[ERROR] 2021-05-16 15:34:04.832 [botify command execution: CommandContext@01c85de9-1ad2-4fb9-a3e6-7538bab1d6cd] CommandManager - Exception while handling command .search -spotify -own -list songs on guild botify                                                                   
net.robinfriedli.botify.exceptions.CommandRuntimeException: java.lang.NullPointerException                                                 
        at net.robinfriedli.botify.command.interceptor.interceptors.CommandExecutionInterceptor.intercept(CommandExecutionInterceptor.java:125) ~[botify-1.0-SNAPSHOT.jar:?]                                                                                                          
        at net.robinfriedli.botify.command.interceptor.AbstractChainableCommandInterceptor.intercept(AbstractChainableCommandInterceptor.java:36) ~[botify-1.0-SNAPSHOT.jar:?]                                                                                                        
        at net.robinfriedli.botify.command.interceptor.AbstractChainableCommandInterceptor.intercept(AbstractChainableCommandInterceptor.java:36) ~[botify-1.0-SNAPSHOT.jar:?]                                                                                                        
        at net.robinfriedli.botify.command.interceptor.AbstractChainableCommandInterceptor.intercept(AbstractChainableCommandInterceptor.java:36) ~[botify-1.0-SNAPSHOT.jar:?]                                                                                                        
        at net.robinfriedli.botify.command.interceptor.AbstractChainableCommandInterceptor.intercept(AbstractChainableCommandInterceptor.java:36) ~[botify-1.0-SNAPSHOT.jar:?]                                                                                                        
        at net.robinfriedli.botify.command.interceptor.AbstractChainableCommandInterceptor.intercept(AbstractChainableCommandInterceptor.java:36) ~[botify-1.0-SNAPSHOT.jar:?]                                                                                                        
        at net.robinfriedli.botify.command.interceptor.CommandInterceptorChain.intercept(CommandInterceptorChain.java:69) ~[botify-1.0-SNAPSHOT.jar:?]                                                                                                                                
        at net.robinfriedli.botify.command.CommandManager.lambda$runCommand$0(CommandManager.java:56) ~[botify-1.0-SNAPSHOT.jar:?]         
        at java.lang.Thread.run(Thread.java:834) [?:?]
        at net.robinfriedli.botify.concurrent.QueuedThread.run(QueuedThread.java:18) ~[botify-1.0-SNAPSHOT.jar:?]                          
        at net.robinfriedli.botify.concurrent.CommandExecutionThread.run(CommandExecutionThread.java:23) ~[botify-1.0-SNAPSHOT.jar:?]      
Caused by: java.lang.NullPointerException 
```

**Comment by dargmuesli** [comment] 2021-05-17 12:54
Hmm, the header doesn't seem to be too long, or do you see that differently? I currently don't know if that issue is on this client's side or if Spotify's servers respond with that status code from time to time and it just feels like it becomes "more likely" the longer an application is running, but it is random after all. Very weird. If anyone knows more, let me know. I'll keep this open for now.

**Comment by robinfriedli** [comment] 2021-05-17 13:00
Yeah not sure what's causing this response either. To clarify though, once the server starts responding with a 431, it does so for every single GetListOfCurrentUsersPlaylistsRequest, so it's not that they become more and more common the longer the service is running.

**Comment by dargmuesli** [comment] 2021-05-17 13:01
Ok, thanks for the clarification!

**Comment by robinfriedli** [comment] 2021-05-18 05:02
Does the API set any cookies?

**Comment by dargmuesli** [comment] 2021-05-19 02:33
To my knowledge, not in this repo's code.

**Comment by dargmuesli** [comment] 2021-09-09 04:48
As we tried narrowing the problem down to an issue within the source code and until now haven't been able to find it, I'll close this issue for now. In case someone is able to provide further useful insight, we can of course reopen this issue. Thank you for your effort!

**Closed by dargmuesli** 2021-09-09 04:48 UTC
Labels: bug, help wanted
