### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseString(Ljava/lang/String;)Lcom/google/gson/JsonElement;

### ISSUE THREAD

**Issue by HenriqueNapimo1** [thelinmichael/spotify-web-api-java#224] opened 2020-08-18 16:37 UTC
I copied exactly the same code of [examples/authorization/client_credentials/ClientCredentialsExample.java](https://github.com/thelinmichael/spotify-web-api-java/blob/master/examples/authorization/client_credentials/ClientCredentialsExample.java) to my project and it didn't work, showing this error message:

```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseString(Ljava/lang/String;)Lcom/google/gson/JsonElement;
	at com.wrapper.spotify.SpotifyHttpManager.getResponseBody(SpotifyHttpManager.java:277)
	at com.wrapper.spotify.SpotifyHttpManager.post(SpotifyHttpManager.java:179)
	at com.wrapper.spotify.requests.AbstractRequest.postJson(AbstractRequest.java:126)
	at com.wrapper.spotify.requests.authorization.client_credentials.ClientCredentialsRequest.execute(ClientCredentialsRequest.java:36)
	at com.henriquenapimo1.david.music.SpotifyAuthorization.clientCredentials_Sync(SpotifyAuthorization.java:28)
	at com.henriquenapimo1.david.music.SpotifyAuthorization.main(SpotifyAuthorization.java:60)

Process finished with exit code 1
```

and my version of the api is 6.0.0 and i also tried to run this with the 6.3.0 and it fails as well

**Comment by dargmuesli** [comment] 2020-08-18 18:52
Cannot reproduce. Maybe your Maven dependencies are outdated? Try a refresh.

**Comment by theo-basty** [comment] 2020-08-20 14:06
I had the same problem after adding the your API today in my project, 
I solved it by explicitly updating GSON from version 2.8.5 to version 2.8.6 in my application's build.gradle
```
dependencies {
    implementation 'com.google.code.gson:gson:2.8.6'
}
```

Don't know why however...
Maybe some weird stuff in way GSON is distributed ?

**Comment by dargmuesli** [comment] 2020-08-20 21:28
Version `6.3.0` is using GSON `2.8.6`:
https://github.com/thelinmichael/spotify-web-api-java/blob/ffa49b93b0441a5f149397bae3eb979182fdf4ed/pom.xml#L70-L74

Don't know what's happening here. If there won't be any more details that allow me to reproduce the issue, I'll close this issue in a few days. It can surely be reopened though ;)

**Comment by HenriqueNapimo1** [comment] 2020-08-23 20:16
> I had the same problem after adding your API today in my project,
> I solved it by explicitly updating GSON from version 2.8.5 to version 2.8.6 in my application's build.gradle
> 
> ```
> dependencies {
>     implementation 'com.google.code.gson:gson:2.8.6'
> }
> ```
> 
> Don't know why however...
> Maybe some weird stuff in way GSON is distributed ?

I tried and IT WORKS! THANK YOU SO MUCH!

**Closed** 2020-08-24 08:13 UTC
