### ISSUE TITLE
Add ability to remove tracks from a playlist

### ISSUE THREAD

**Issue by erikhofer** [thelinmichael/spotify-web-api-java#58] opened 2016-08-04 06:44 UTC
At the moment you can only add tracks to a playlist but not remove them.

https://developer.spotify.com/web-api/remove-tracks-playlist/

**Comment by Dargmuesli** [comment] 2016-08-08 23:42
There is already pull request #46 request for that. But it seems like @thelinmichael dumped this project. Maybe I'll setup a fork containing these features.

**Comment by thelinmichael** [comment] 2016-08-11 05:56
Thanks for opening the issue @erikhofer. @Dargmuesli, I'd be extremely happy if you wanted to get involved in this project, either through your own fork or an entirely new client. Please reach out to me either via Twitter or email.

Closing this issue since it's indeed a duplicate of #19.

**Closed by thelinmichael** 2016-08-11 05:56 UTC
